### ISSUE TITLE
拖动结束后父组件的data参数是如何变成子组件传的options.bindData参数的

### ISSUE THREAD

**Issue by bangxingni** [NightCatSama/vue-bilibili-nav#1]
如标题，绑定的参数是options ，dragEnd(拖拽结束时)根据对象间 的引用关系改变的是prop的options.bindData里面的参数，为何父组件中的data参数变了呢，父组件data并没有绑定到子组件，初学vue,请教大佬。

**Comment by NightCatSama** [comment]
因为在 javascript 中对象和数组是引用类型传递的，子组件修改就会影响到父组件。

**Comment by bangxingni** [comment]
明白了，	var a = [1,2,3,4,5];
		var b = a;
		b.splice(1, 1);
		alert(a);  这里改变的是数组对象，它们的引用还是指向这个数组，thank you
